// <auto-generated />
using System;
using EPR.Payment.Service.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPR.Payment.Service.Common.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.AccreditationFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FeesPerSite")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RegulatorId")
                        .HasColumnType("int");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TonnesOver")
                        .HasColumnType("int");

                    b.Property<int>("TonnesUpTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RegulatorId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("AccreditationFees", "Lookup");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Group", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Producer Type",
                            Type = "ProducerType"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Compliance Scheme",
                            Type = "ComplianceScheme"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Producer Subsidiaries",
                            Type = "ProducerSubsidiaries"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Compliance Scheme Subsidiaries",
                            Type = "ComplianceSchemeSubsidiaries"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Producer re-submitting a report",
                            Type = "ProducerResubmission"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Compliance Scheme re-submitting a report",
                            Type = "ComplianceSchemeResubmission"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Exporters",
                            Type = "Exporters"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reprocessors",
                            Type = "Reprocessors"
                        });
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatus", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Status = "Initiated"
                        },
                        new
                        {
                            Id = 1,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Success"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Failed"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Error"
                        },
                        new
                        {
                            Id = 5,
                            Status = "UserCancelled"
                        });
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.RegistrationFees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RegulatorId")
                        .HasColumnType("int");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RegulatorId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("RegistrationFees", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 262000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 1,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 262000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 2,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 262000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 3,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 262000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 4,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 121600m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 1,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 121600m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 2,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 121600m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 3,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 121600m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 4,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 9,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 1,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 2,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 11,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 3,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 4,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 13,
                            Amount = 168500m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 1,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 168500m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 2,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 168500m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 3,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 168500m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 4,
                            SubGroupId = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = 63100m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 1,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 63100m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 2,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 63100m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 3,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 63100m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 4,
                            SubGroupId = 2
                        },
                        new
                        {
                            Id = 21,
                            Amount = 1380400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 1,
                            SubGroupId = 3
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1380400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 2,
                            SubGroupId = 3
                        },
                        new
                        {
                            Id = 23,
                            Amount = 1380400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 3,
                            SubGroupId = 3
                        },
                        new
                        {
                            Id = 24,
                            Amount = 1380400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 4,
                            SubGroupId = 3
                        },
                        new
                        {
                            Id = 25,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 1,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 26,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 2,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 27,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 3,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 28,
                            Amount = 257900m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 4,
                            SubGroupId = 4
                        },
                        new
                        {
                            Id = 29,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 1,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 30,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 2,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 31,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 3,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 32,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 4,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 33,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 1,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 34,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 2,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 35,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 3,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 36,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 3,
                            RegulatorId = 4,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 37,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 1,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 38,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 2,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 39,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 3,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 40,
                            Amount = 55800m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 4,
                            SubGroupId = 5
                        },
                        new
                        {
                            Id = 41,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 1,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 42,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 2,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 43,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 3,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 44,
                            Amount = 14000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 4,
                            RegulatorId = 4,
                            SubGroupId = 6
                        },
                        new
                        {
                            Id = 45,
                            Amount = 71400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 5,
                            RegulatorId = 1,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 46,
                            Amount = 71400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 5,
                            RegulatorId = 2,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 47,
                            Amount = 71400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 5,
                            RegulatorId = 3,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 48,
                            Amount = 71400m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 5,
                            RegulatorId = 4,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 49,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 1,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 50,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 2,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 51,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 3,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 52,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            RegulatorId = 4,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 53,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 1,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 54,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 2,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 55,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 3,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 56,
                            Amount = 33200m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 2,
                            RegulatorId = 4,
                            SubGroupId = 8
                        },
                        new
                        {
                            Id = 57,
                            Amount = 43000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 6,
                            RegulatorId = 1,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 58,
                            Amount = 43000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 6,
                            RegulatorId = 2,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 59,
                            Amount = 43000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 6,
                            RegulatorId = 3,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 60,
                            Amount = 43000m,
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 6,
                            RegulatorId = 4,
                            SubGroupId = 7
                        },
                        new
                        {
                            Id = 61,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 62,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 63,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 64,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 65,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 66,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 1,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 67,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 68,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 69,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 70,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 71,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 72,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 2,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 73,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 74,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 75,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 76,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 77,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 78,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 3,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 79,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 80,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 81,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 82,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 83,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 84,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 7,
                            RegulatorId = 4,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 85,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 86,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 87,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 88,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 89,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 90,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 1,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 91,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 92,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 93,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 94,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 95,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 96,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 2,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 97,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 98,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 99,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 100,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 101,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 102,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 3,
                            SubGroupId = 14
                        },
                        new
                        {
                            Id = 103,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 9
                        },
                        new
                        {
                            Id = 104,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 10
                        },
                        new
                        {
                            Id = 105,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 11
                        },
                        new
                        {
                            Id = 106,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 12
                        },
                        new
                        {
                            Id = 107,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 13
                        },
                        new
                        {
                            Id = 108,
                            Amount = 2921m,
                            EffectiveFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(9999, 8, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            GroupId = 8,
                            RegulatorId = 4,
                            SubGroupId = 14
                        });
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.Regulator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Regulator", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "England",
                            Type = "GB-ENG"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Scotland",
                            Type = "GB-SCT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wales",
                            Type = "GB-WLS"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Northern Ireland",
                            Type = "GB-NIR"
                        });
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.SubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SubGroup", "Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Large producer",
                            Type = "Large"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Small producer",
                            Type = "Small"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Registration",
                            Type = "Registration"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Online Market",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Up to 20",
                            Type = "UpTo20"
                        },
                        new
                        {
                            Id = 6,
                            Description = "More than 20",
                            Type = "MoreThan20"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Re-submitting a report",
                            Type = "ReSubmitting"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Late Fee",
                            Type = "LateFee"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Aluminium",
                            Type = "Aluminium"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Glass",
                            Type = "Glass"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Paper, board or fibre-based composite material",
                            Type = "PaperOrBoardOrFibreBasedCompositeMaterial"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Plastic",
                            Type = "Plastic"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Steel",
                            Type = "Steel"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Wood",
                            Type = "Wood"
                        });
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.OfflinePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("OfflinePayment", (string)null);
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.OnlinePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(6);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(7);

                    b.Property<string>("GovPayPaymentId")
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(4);

                    b.Property<string>("GovPayStatus")
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(5);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<Guid>("UpdatedByOrgId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("GovPayPaymentId")
                        .IsUnique()
                        .HasFilter("[GovPayPaymentId] IS NOT NULL");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("OnlinePayment", (string)null);
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(9);

                    b.Property<Guid>("ExternalPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("InternalStatusId")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("ReasonForPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(8);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(6);

                    b.Property<string>("Regulator")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(11);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ExternalPaymentId")
                        .IsUnique();

                    b.HasIndex("InternalStatusId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.AccreditationFee", b =>
                {
                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.Regulator", "Regulator")
                        .WithMany()
                        .HasForeignKey("RegulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.SubGroup", "SubGroup")
                        .WithMany()
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Regulator");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.RegistrationFees", b =>
                {
                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.Group", "Group")
                        .WithMany("RegistrationFees")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.Regulator", "Regulator")
                        .WithMany("RegistrationFees")
                        .HasForeignKey("RegulatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.SubGroup", "SubGroup")
                        .WithMany("RegistrationFees")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Regulator");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.OfflinePayment", b =>
                {
                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Payment", "Payment")
                        .WithOne("OfflinePayment")
                        .HasForeignKey("EPR.Payment.Service.Common.Data.DataModels.OfflinePayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.OnlinePayment", b =>
                {
                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Payment", "Payment")
                        .WithOne("OnlinePayment")
                        .HasForeignKey("EPR.Payment.Service.Common.Data.DataModels.OnlinePayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Payment", b =>
                {
                    b.HasOne("EPR.Payment.Service.Common.Data.DataModels.Lookups.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("InternalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.Group", b =>
                {
                    b.Navigation("RegistrationFees");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.Regulator", b =>
                {
                    b.Navigation("RegistrationFees");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Lookups.SubGroup", b =>
                {
                    b.Navigation("RegistrationFees");
                });

            modelBuilder.Entity("EPR.Payment.Service.Common.Data.DataModels.Payment", b =>
                {
                    b.Navigation("OfflinePayment")
                        .IsRequired();

                    b.Navigation("OnlinePayment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
