variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprpaymentbackend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprpaymentbackendrepository'
  serviceName: 'prdrwdwebwa1425'
  kvName: PRDRWDINFKV1401
  sqlDBserver: 'prerwddbssq1401.database.windows.net'
  sqlDB: 'prd1_feespayment'
  acr.Subscription: 'AZR-RWD-PRD1'
