variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'eprpaymentbackend'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'eprpaymentbackendrepository'
- name: serviceName
  value: 'prdrwdwebwa1425'
- name: kvName
  value: PRDRWDINFKV1401
- name: sqlDBserver
  value: 'prdrwddbssq1401.database.windows.net'
- name: sqlDB
  value: 'prd1_feespayment'
- name: acr.Subscription
  value: 'AZR-RWD-PRD1'
